# Generated by Django 5.2.5 on 2025-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
